on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - run: npm install
      - run: npx prettier --check .

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - run: npm install

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

      - name: Upload test results to BuildPulse for flaky test detection
        # Only run this step for branches where where we have access to secrets.
        # Run this step even when the tests fail. Skip if the workflow is cancelled.
        if: env.HAS_SECRETS == 'true' && !cancelled()
        env:
          HAS_SECRETS: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID != '' && secrets.BUILDPULSE_SECRET_ACCESS_KEY != '' }}
        uses: Workshop64/buildpulse-action@main
        with:
          account: 2988
          repository: 455353795
          path: ./test-results.xml
          key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
          secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
